name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

# bashを使うようにしてpipefailを有効にする
# https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
    - if: matrix.os == 'macos-15'
      run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'
    - if: startsWith(matrix.os, 'macos')
      name: Run tests
      run: swift test 2>&1 | xcbeautify
    - if: startsWith(matrix.os, 'ubuntu')
      run: LD_LIBRARY_PATH="$PWD/lib/x86_64:$LD_LIBRARY_PATH" swift test
